channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow
  - cffi==1.15.0
  - configparser==5.2.0
  - cython==0.29.28
  - cytoolz==0.11.0
  - defusedxml==0.7.1
  - distributed==2022.2.1
  - lightgbm==3.3.2
  - matplotlib==3.5.1
  - pandas==1.4.2
  - python-snappy==0.6.0
  - typing-extensions==4.1.1
name: mlflow-env
